import type { YachtRow } from "./schema";

export const yachts: YachtRow[] = [
  {
    id: 1,
    slug: "serenity-seeker",
    name: "Serenity Seeker",
    destination_id: 1,
    price_per_day: 499,
    max_guests: 10,
    beds: 7,
    crew: 4,
    length_m: 28,
    description:
      "A flagship motor yacht built for long Caribbean passages in total comfort. Wide sun decks, a shaded aft lounge and a professional crew of four make Serenity Seeker the fleet favourite for families and groups.",
    image_path: "/assets/yacht-serenity-seeker.webp",
    is_featured: true,
  },
  {
    id: 2,
    slug: "ocean-whisperer",
    name: "Ocean Whisperer",
    destination_id: 2,
    price_per_day: 299,
    max_guests: 5,
    beds: 3,
    crew: 2,
    length_m: 18,
    description:
      "An agile cruiser sized for couples and small parties, ideal for hopping between the villages of the Amalfi Coast. Shallow draft lets her anchor where the big boats cannot.",
    image_path: "/assets/yacht-ocean-whisperer.webp",
    is_featured: true,
  },
  {
    id: 3,
    slug: "majestic-pearl",
    name: "Majestic Pearl",
    destination_id: 3,
    price_per_day: 799,
    max_guests: 14,
    beds: 10,
    crew: 6,
    length_m: 36,
    description:
      "The largest yacht in our fleet — a tri-deck statement piece with a jacuzzi foredeck, formal dining for twelve and a full water-toy garage. Made for the French Riviera season.",
    image_path: "/assets/yacht-majestic-pearl.webp",
    is_featured: true,
  },
  {
    id: 4,
    slug: "celestial-voyager",
    name: "Celestial Voyager",
    destination_id: 4,
    price_per_day: 399,
    max_guests: 8,
    beds: 6,
    crew: 3,
    length_m: 24,
    description:
      "A blue-water explorer fitted for reef country: snorkel platform, glass-bottom tender and long-range tanks for unhurried cruising through the Whitsundays.",
    image_path: "/assets/yacht-celestial-voyager.webp",
    is_featured: true,
  },
  {
    id: 5,
    slug: "carpe-diem",
    name: "Carpe Diem",
    destination_id: 5,
    price_per_day: 199,
    max_guests: 3,
    beds: 2,
    crew: 1,
    length_m: 14,
    description:
      "Our most affordable charter — a nimble day-sailer with two cabins, perfect for island-hopping the Aegean with a skipper who knows every hidden cove.",
    image_path: "/assets/yacht-carpe-diem.webp",
    is_featured: true,
  },
];
